/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/audit-logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List audit entries (newest first) */
    get: operations["list_audit_logs_api_v1_audit_logs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/candidate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The candidate profile (imported from candidate/profile.yaml on first use) */
    get: operations["get_candidate_api_v1_candidate_get"];
    /** Replace the profile (optimistic concurrency on profile_version) */
    put: operations["update_candidate_api_v1_candidate_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/candidate/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download the profile as YAML (private contact details only on request) */
    get: operations["export_candidate_api_v1_candidate_export_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/candidate/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reload the profile from candidate/profile.yaml (+ profile.local.yaml) */
    post: operations["import_candidate_api_v1_candidate_import_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/candidate/master-cv": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Master CV versions, newest first */
    get: operations["list_master_cvs_api_v1_candidate_master_cv_get"];
    put?: never;
    /** Upload a master CV (.docx or .pdf); it is parsed into a draft to review */
    post: operations["upload_master_cv_api_v1_candidate_master_cv_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/candidate/master-cv/{version_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A master CV version with its parsed structure */
    get: operations["get_master_cv_api_v1_candidate_master_cv__version_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/candidate/master-cv/{version_id}/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm a draft: it becomes the active master CV and rebuilds the fact base */
    post: operations["confirm_master_cv_api_v1_candidate_master_cv__version_id__confirm_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/candidate/master-cv/{version_id}/file": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download the original uploaded file */
    get: operations["download_master_cv_api_v1_candidate_master_cv__version_id__file_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/candidate/master-cv/{version_id}/revise": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Copy a confirmed version into a new editable draft */
    post: operations["revise_master_cv_api_v1_candidate_master_cv__version_id__revise_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/candidate/master-cv/{version_id}/structure": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Save corrections to a draft (confirmed versions are read-only) */
    put: operations["update_master_cv_structure_api_v1_candidate_master_cv__version_id__structure_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/candidate/skills": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Declared and CV skills with their evidence in the confirmed master CV */
    get: operations["list_skills_api_v1_candidate_skills_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/companies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Watchlist companies (by name) */
    get: operations["list_companies_api_v1_companies_get"];
    put?: never;
    /** Add a company to the watchlist */
    post: operations["create_company_api_v1_companies_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/companies/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create or update the companies listed in crawler/companies.yaml */
    post: operations["import_companies_api_v1_companies_import_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/companies/{company_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One watchlist company */
    get: operations["get_company_api_v1_companies__company_id__get"];
    put?: never;
    post?: never;
    /** Remove a company from the watchlist (its jobs are kept) */
    delete: operations["delete_company_api_v1_companies__company_id__delete"];
    options?: never;
    head?: never;
    /** Update a watchlist company (only the fields sent) */
    patch: operations["update_company_api_v1_companies__company_id__patch"];
    trace?: never;
  };
  "/api/v1/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness probe
     * @description The process is up and serving requests.
     */
    get: operations["live_api_v1_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness probe
     * @description Database reachable, migrations at head, Redis reachable, storage writable.
     *
     *     Public endpoint: failure details are hidden (see `/system/status` for details).
     */
    get: operations["ready_api_v1_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/job-sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Job sources and their policy */
    get: operations["list_job_sources_api_v1_job_sources_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List jobs (default: posted in the lookback window) */
    get: operations["list_jobs_api_v1_jobs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import a job URL (LinkedIn or any public posting); stored, never fetched */
    post: operations["import_job_api_v1_jobs_import_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/import/email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import the job links of a job-alert email (used by the n8n workflow) */
    post: operations["import_email_api_v1_jobs_import_email_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Discovery statistics for the dashboard */
    get: operations["job_stats_api_v1_jobs_stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Job detail with its other listings and pipeline entries */
    get: operations["get_job_api_v1_jobs__job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/{job_id}/track": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Queue a job for the candidate (e.g. a job whose posting date is unknown) */
    post: operations["track_job_api_v1_jobs__job_id__track_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List automation runs (newest first) */
    get: operations["list_runs_api_v1_runs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/diagnostic": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a system self-test run on a worker */
    post: operations["start_diagnostic_api_v1_runs_diagnostic_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/discovery": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a job discovery run on a worker */
    post: operations["start_discovery_api_v1_runs_discovery_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Run detail with its event timeline */
    get: operations["get_run_api_v1_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/system/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Safe configuration and roadmap */
    get: operations["system_info_api_v1_system_info_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/system/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detailed component health */
    get: operations["system_status_api_v1_system_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ApplicationDefaults */
    "ApplicationDefaults-Input": {
      /** Earliest Start Date */
      earliest_start_date?: string | null;
      /** Languages */
      languages?: components["schemas"]["SpokenLanguage"][] | null;
      /** Notice Period */
      notice_period?: string | null;
      /** Preferred Work Modes */
      preferred_work_modes?: components["schemas"]["WorkMode"][] | null;
      /** Salary Expectations */
      salary_expectations?: components["schemas"]["SalaryExpectation-Input"][] | null;
    };
    /** ApplicationDefaults */
    "ApplicationDefaults-Output": {
      /** Earliest Start Date */
      earliest_start_date: string | null;
      /** Languages */
      languages: components["schemas"]["SpokenLanguage"][] | null;
      /** Notice Period */
      notice_period: string | null;
      /** Preferred Work Modes */
      preferred_work_modes: components["schemas"]["WorkMode"][] | null;
      /** Salary Expectations */
      salary_expectations: components["schemas"]["SalaryExpectation-Output"][] | null;
    };
    /**
     * ApplicationStatus
     * @enum {string}
     */
    ApplicationStatus:
      | "DISCOVERED"
      | "ANALYZED"
      | "QUALIFIED"
      | "CV_GENERATED"
      | "READY_FOR_REVIEW"
      | "APPROVED"
      | "SUBMITTED"
      | "HR_SCREEN"
      | "INTERVIEW"
      | "OFFER"
      | "REJECTED"
      | "WITHDRAWN"
      | "BLOCKED"
      | "MANUAL_ACTION_REQUIRED";
    /**
     * AtsType
     * @enum {string}
     */
    AtsType:
      | "GREENHOUSE"
      | "LEVER"
      | "ASHBY"
      | "SMARTRECRUITERS"
      | "WORKDAY"
      | "LINKEDIN"
      | "INDEED"
      | "GENERIC"
      | "OTHER";
    /** AuditLogEntry */
    AuditLogEntry: {
      /** Action */
      action: string;
      /** Actor */
      actor: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Details */
      details: {
        [key: string]: unknown;
      };
      /** Entity Id */
      entity_id: string | null;
      /** Entity Type */
      entity_type: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Request Id */
      request_id: string | null;
      /** Sequence */
      sequence: number;
    };
    /** AuditLogPage */
    AuditLogPage: {
      /** Items */
      items: components["schemas"]["AuditLogEntry"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /**
     * AuthorizationStatus
     * @enum {string}
     */
    AuthorizationStatus: "citizen" | "permanent_resident" | "work_permit" | "other";
    /** Body_upload_master_cv_api_v1_candidate_master_cv_post */
    Body_upload_master_cv_api_v1_candidate_master_cv_post: {
      /**
       * File
       * @description The CV file (.docx or .pdf)
       */
      file: string;
    };
    /** CandidateProfile */
    "CandidateProfile-Input": {
      application_defaults?: components["schemas"]["ApplicationDefaults-Input"];
      contact?: components["schemas"]["Contact-Input"];
      /** Core Skills */
      core_skills?: string[];
      cv_policy?: components["schemas"]["CvPolicy-Input"];
      identity: components["schemas"]["Identity-Input"];
      relocation?: components["schemas"]["Relocation-Input"];
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
      targets?: components["schemas"]["Targets-Input"];
      work_authorization?: components["schemas"]["WorkAuthorization-Input"];
    };
    /** CandidateProfile */
    "CandidateProfile-Output": {
      application_defaults: components["schemas"]["ApplicationDefaults-Output"];
      contact: components["schemas"]["Contact-Output"];
      /** Core Skills */
      core_skills: string[];
      cv_policy: components["schemas"]["CvPolicy-Output"];
      identity: components["schemas"]["Identity-Output"];
      relocation: components["schemas"]["Relocation-Output"];
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
      targets: components["schemas"]["Targets-Output"];
      work_authorization: components["schemas"]["WorkAuthorization-Output"];
    };
    /** CandidateRead */
    CandidateRead: {
      active_master_cv: components["schemas"]["CvVersionSummary"] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Needs User Input
       * @description Profile fields that are empty and must be provided by the user
       */
      needs_user_input: string[];
      profile: components["schemas"]["CandidateProfile-Output"];
      /** Profile Version */
      profile_version: number;
      /** Slug */
      slug: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** CandidateSkillRead */
    CandidateSkillRead: {
      /** Category */
      category: string | null;
      /** Evidence */
      evidence: components["schemas"]["EvidenceItem"][];
      /** Name */
      name: string;
      /** Normalized Name */
      normalized_name: string;
      /** Sources */
      sources: components["schemas"]["SkillSource"][];
      strength: components["schemas"]["SkillStrength"];
    };
    /** CandidateUpdate */
    CandidateUpdate: {
      profile: components["schemas"]["CandidateProfile-Input"];
      /**
       * Profile Version
       * @description The version being edited; a stale version is rejected with 409
       */
      profile_version: number;
    };
    /** CompanyCreate */
    CompanyCreate: {
      /**
       * Ats Type
       * @default GENERIC
       * @enum {string}
       */
      ats_type:
        "GREENHOUSE" | "LEVER" | "ASHBY" | "SMARTRECRUITERS" | "WORKDAY" | "GENERIC" | "OTHER";
      /** Board Token */
      board_token?: string | null;
      /** Career Url */
      career_url: string;
      /** Country Code */
      country_code?: string | null;
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /** Name */
      name: string;
      /** Notes */
      notes?: string | null;
      /** Target Roles */
      target_roles?: string[];
    };
    /** CompanyImportResult */
    CompanyImportResult: {
      /** Created */
      created: number;
      /** Unchanged */
      unchanged: number;
      /** Updated */
      updated: number;
    };
    /** CompanyRead */
    CompanyRead: {
      /** Ats Type */
      ats_type: string;
      /** Board Token */
      board_token: string | null;
      /** Career Url */
      career_url: string;
      /** Country */
      country: string | null;
      /** Country Code */
      country_code: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Enabled */
      enabled: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Job Count
       * @description Primary job records linked to this company
       */
      job_count: number;
      /** Last Check Status */
      last_check_status: string | null;
      /** Last Checked At */
      last_checked_at: string | null;
      /** Name */
      name: string;
      /** Notes */
      notes: string | null;
      /** Target Roles */
      target_roles: string[];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * CompanyUpdate
     * @description Partial update: only the fields sent are changed (``null`` clears optional fields).
     */
    CompanyUpdate: {
      /** Ats Type */
      ats_type?:
        | ("GREENHOUSE" | "LEVER" | "ASHBY" | "SMARTRECRUITERS" | "WORKDAY" | "GENERIC" | "OTHER")
        | null;
      /** Board Token */
      board_token?: string | null;
      /** Career Url */
      career_url?: string | null;
      /** Country Code */
      country_code?: string | null;
      /** Enabled */
      enabled?: boolean | null;
      /** Name */
      name?: string | null;
      /** Notes */
      notes?: string | null;
      /** Target Roles */
      target_roles?: string[] | null;
    };
    /** ComponentHealth */
    ComponentHealth: {
      /** Critical */
      critical: boolean;
      /** Detail */
      detail?: string | null;
      /** Latency Ms */
      latency_ms?: number | null;
      /** Name */
      name: string;
      status: components["schemas"]["ComponentStatus"];
    };
    /**
     * ComponentStatus
     * @enum {string}
     */
    ComponentStatus: "ok" | "degraded" | "down";
    /**
     * Contact
     * @description Private: stored in the database, never committed to Git, hidden from default exports.
     */
    "Contact-Input": {
      /** Address */
      address?: string | null;
      /** Email */
      email?: string | null;
      /** Github Url */
      github_url?: string | null;
      /** Linkedin Url */
      linkedin_url?: string | null;
      /** Phone */
      phone?: string | null;
      /** Portfolio Url */
      portfolio_url?: string | null;
    };
    /**
     * Contact
     * @description Private: stored in the database, never committed to Git, hidden from default exports.
     */
    "Contact-Output": {
      /** Address */
      address: string | null;
      /** Email */
      email: string | null;
      /** Github Url */
      github_url: string | null;
      /** Linkedin Url */
      linkedin_url: string | null;
      /** Phone */
      phone: string | null;
      /** Portfolio Url */
      portfolio_url: string | null;
    };
    /** ContactInfo */
    "ContactInfo-Input": {
      /** Emails */
      emails?: string[];
      /** Links */
      links?: string[];
      /** Phones */
      phones?: string[];
    };
    /** ContactInfo */
    "ContactInfo-Output": {
      /** Emails */
      emails: string[];
      /** Links */
      links: string[];
      /** Phones */
      phones: string[];
    };
    /**
     * CvKind
     * @enum {string}
     */
    CvKind: "MASTER" | "TAILORED";
    /** CvPolicy */
    "CvPolicy-Input": {
      /**
       * Allow Title Changes
       * @default false
       */
      allow_title_changes: boolean;
    };
    /** CvPolicy */
    "CvPolicy-Output": {
      /**
       * Allow Title Changes
       * @default false
       */
      allow_title_changes: boolean;
    };
    /**
     * CvStatus
     * @enum {string}
     */
    CvStatus: "PARSED" | "CONFIRMED" | "SUPERSEDED";
    /** CvVersionDetail */
    CvVersionDetail: {
      /** Confirmed At */
      confirmed_at: string | null;
      /** Content Type */
      content_type: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Extracted Text
       * @description Plain text extracted from the uploaded file
       */
      extracted_text: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      kind: components["schemas"]["CvKind"];
      /** Original Filename */
      original_filename: string;
      /** Parser Version */
      parser_version: string;
      /** Revised From Id */
      revised_from_id: string | null;
      /** Sha256 */
      sha256: string;
      /** Size Bytes */
      size_bytes: number;
      status: components["schemas"]["CvStatus"];
      structure: components["schemas"]["ParsedCV-Output"];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Version */
      version: number;
      /**
       * Warning Count
       * @description Warnings to review in the parsed structure
       */
      warning_count: number;
    };
    /** CvVersionSummary */
    CvVersionSummary: {
      /** Confirmed At */
      confirmed_at: string | null;
      /** Content Type */
      content_type: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      kind: components["schemas"]["CvKind"];
      /** Original Filename */
      original_filename: string;
      /** Parser Version */
      parser_version: string;
      /** Revised From Id */
      revised_from_id: string | null;
      /** Sha256 */
      sha256: string;
      /** Size Bytes */
      size_bytes: number;
      status: components["schemas"]["CvStatus"];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Version */
      version: number;
      /**
       * Warning Count
       * @description Warnings to review in the parsed structure
       */
      warning_count: number;
    };
    /** DateRange */
    "DateRange-Input": {
      end?: components["schemas"]["YearMonth-Input"] | null;
      /**
       * Is Current
       * @default false
       */
      is_current: boolean;
      start?: components["schemas"]["YearMonth-Input"] | null;
      /**
       * Text
       * @description The dates as written in the CV
       */
      text: string;
    };
    /** DateRange */
    "DateRange-Output": {
      end: components["schemas"]["YearMonth-Output"] | null;
      /**
       * Is Current
       * @default false
       */
      is_current: boolean;
      start: components["schemas"]["YearMonth-Output"] | null;
      /**
       * Text
       * @description The dates as written in the CV
       */
      text: string;
    };
    /** EducationEntry */
    "EducationEntry-Input": {
      /** Bullets */
      bullets?: string[];
      dates?: components["schemas"]["DateRange-Input"] | null;
      /** Degree */
      degree: string;
      /** Details */
      details?: string[];
      /** Institution */
      institution?: string | null;
      /** Location */
      location?: string | null;
    };
    /** EducationEntry */
    "EducationEntry-Output": {
      /** Bullets */
      bullets: string[];
      dates: components["schemas"]["DateRange-Output"] | null;
      /** Degree */
      degree: string;
      /** Details */
      details: string[];
      /** Institution */
      institution: string | null;
      /** Location */
      location: string | null;
    };
    /**
     * EmailImportRequest
     * @description A job-alert email (forwarded by n8n or pasted). Only job links are extracted.
     */
    EmailImportRequest: {
      /** Received At */
      received_at?: string | null;
      /** Sender */
      sender?: string | null;
      /**
       * Subject
       * @default
       */
      subject: string;
      /**
       * Text
       * @description HTML or plain-text body
       */
      text: string;
    };
    /** EmailImportResult */
    EmailImportResult: {
      /** Links Found */
      links_found: number;
      /** Results */
      results: components["schemas"]["JobImportResult"][];
    };
    /**
     * EmploymentType
     * @enum {string}
     */
    EmploymentType: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "TEMPORARY" | "INTERNSHIP" | "UNKNOWN";
    /** ErrorDetail */
    ErrorDetail: {
      /**
       * Code
       * @description Stable machine-readable error code
       */
      code: string;
      /** Details */
      details?: unknown | null;
      /** Message */
      message: string;
      /** Request Id */
      request_id?: string | null;
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components["schemas"]["ErrorDetail"];
    };
    /**
     * EventLevel
     * @enum {string}
     */
    EventLevel: "DEBUG" | "INFO" | "WARNING" | "ERROR";
    /** EvidenceItem */
    EvidenceItem: {
      /** Excerpt */
      excerpt: string;
      /** Section */
      section: string;
    };
    /** ExperienceEntry */
    "ExperienceEntry-Input": {
      /** Bullets */
      bullets?: string[];
      dates?: components["schemas"]["DateRange-Input"] | null;
      /** Details */
      details?: string[];
      /** Employer */
      employer?: string | null;
      /** Location */
      location?: string | null;
      /** Title */
      title: string;
    };
    /** ExperienceEntry */
    "ExperienceEntry-Output": {
      /** Bullets */
      bullets: string[];
      dates: components["schemas"]["DateRange-Output"] | null;
      /** Details */
      details: string[];
      /** Employer */
      employer: string | null;
      /** Location */
      location: string | null;
      /** Title */
      title: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Identity */
    "Identity-Input": {
      /** Full Name */
      full_name: string;
      /** Headline */
      headline?: string | null;
      location?: components["schemas"]["Location-Input"];
      /** Nationality */
      nationality?: string | null;
    };
    /** Identity */
    "Identity-Output": {
      /** Full Name */
      full_name: string;
      /** Headline */
      headline: string | null;
      location: components["schemas"]["Location-Output"];
      /** Nationality */
      nationality: string | null;
    };
    /** JobApplicationRead */
    JobApplicationRead: {
      /**
       * Candidate Id
       * Format: uuid
       */
      candidate_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      status: components["schemas"]["ApplicationStatus"];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** JobDetail */
    JobDetail: {
      /** @description Pipeline status for the candidate, when the job is queued */
      application_status: components["schemas"]["ApplicationStatus"] | null;
      /** Application Url */
      application_url: string | null;
      /** Applications */
      applications: components["schemas"]["JobApplicationRead"][];
      ats_type: components["schemas"]["AtsType"];
      /** Canonical Url */
      canonical_url: string | null;
      /** Company */
      company: string;
      /** Company Id */
      company_id: string | null;
      /** Company Url */
      company_url: string | null;
      /** Country */
      country: string | null;
      /** Country Code */
      country_code: string | null;
      /** Description */
      description: string;
      /**
       * Discovered At
       * Format: date-time
       */
      discovered_at: string;
      /** Discovery Run Id */
      discovery_run_id: string | null;
      /**
       * Duplicate Count
       * @default 0
       */
      duplicate_count: number;
      /** Duplicate Of Id */
      duplicate_of_id: string | null;
      /** Duplicates */
      duplicates: components["schemas"]["JobListing"][];
      /** Education Requirements */
      education_requirements: string | null;
      employment_type: components["schemas"]["EmploymentType"];
      /** Experience Requirements */
      experience_requirements: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Languages */
      languages: string[];
      /**
       * Last Seen At
       * Format: date-time
       */
      last_seen_at: string;
      /** Location */
      location: string | null;
      /** Posted At */
      posted_at: string | null;
      /** Posting Date Basis */
      posting_date_basis: string | null;
      posting_date_status: components["schemas"]["PostingDateStatus"];
      /** Preferred Skills */
      preferred_skills: string[];
      /** @description The primary record, when this listing is a duplicate */
      primary: components["schemas"]["JobListing"] | null;
      /** Raw Content */
      raw_content: {
        [key: string]: unknown;
      };
      /** Relocation Information */
      relocation_information: string | null;
      remote_status: components["schemas"]["RemoteStatus"];
      /** Required Skills */
      required_skills: string[];
      /** Responsibilities */
      responsibilities: string[];
      /** Salary Currency */
      salary_currency: string | null;
      /** Salary Max */
      salary_max: number | null;
      /** Salary Min */
      salary_min: number | null;
      /** Salary Period */
      salary_period: string | null;
      seniority: components["schemas"]["Seniority"];
      /** Source */
      source: string;
      /** Source Job Id */
      source_job_id: string | null;
      /** Title */
      title: string;
      /** Visa Information */
      visa_information: string | null;
      window_status: components["schemas"]["WindowStatus"];
    };
    /**
     * JobImportRequest
     * @description A job the user found (e.g. a LinkedIn posting). The URL is stored, never fetched.
     */
    JobImportRequest: {
      /** Company */
      company?: string | null;
      /** Description */
      description?: string | null;
      /** Location */
      location?: string | null;
      /** Posted At */
      posted_at?: string | null;
      /**
       * Posted Text
       * @description Relative date as shown, e.g. "2 hours ago"
       */
      posted_text?: string | null;
      /** Title */
      title?: string | null;
      /** Url */
      url: string;
    };
    /** JobImportResult */
    JobImportResult: {
      /** Application Created */
      application_created: boolean;
      /** Created */
      created: boolean;
      /** Duplicate */
      duplicate: boolean;
      job: components["schemas"]["JobRead"];
    };
    /**
     * JobListing
     * @description Another listing of the same job (a duplicate record from another source).
     */
    JobListing: {
      /** Application Url */
      application_url: string | null;
      /** Company */
      company: string;
      /**
       * Discovered At
       * Format: date-time
       */
      discovered_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Posted At */
      posted_at: string | null;
      posting_date_status: components["schemas"]["PostingDateStatus"];
      /** Source */
      source: string;
      /** Title */
      title: string;
    };
    /** JobPage */
    JobPage: {
      /** Items */
      items: components["schemas"]["JobRead"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
      window: components["schemas"]["WindowRead"];
    };
    /** JobRead */
    JobRead: {
      /** @description Pipeline status for the candidate, when the job is queued */
      application_status: components["schemas"]["ApplicationStatus"] | null;
      /** Application Url */
      application_url: string | null;
      ats_type: components["schemas"]["AtsType"];
      /** Canonical Url */
      canonical_url: string | null;
      /** Company */
      company: string;
      /** Company Id */
      company_id: string | null;
      /** Country */
      country: string | null;
      /** Country Code */
      country_code: string | null;
      /**
       * Discovered At
       * Format: date-time
       */
      discovered_at: string;
      /**
       * Duplicate Count
       * @default 0
       */
      duplicate_count: number;
      /** Duplicate Of Id */
      duplicate_of_id: string | null;
      employment_type: components["schemas"]["EmploymentType"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Last Seen At
       * Format: date-time
       */
      last_seen_at: string;
      /** Location */
      location: string | null;
      /** Posted At */
      posted_at: string | null;
      /** Posting Date Basis */
      posting_date_basis: string | null;
      posting_date_status: components["schemas"]["PostingDateStatus"];
      remote_status: components["schemas"]["RemoteStatus"];
      /** Salary Currency */
      salary_currency: string | null;
      /** Salary Max */
      salary_max: number | null;
      /** Salary Min */
      salary_min: number | null;
      /** Salary Period */
      salary_period: string | null;
      seniority: components["schemas"]["Seniority"];
      /** Source */
      source: string;
      /** Source Job Id */
      source_job_id: string | null;
      /** Title */
      title: string;
      window_status: components["schemas"]["WindowStatus"];
    };
    /** JobSourceRead */
    JobSourceRead: {
      /** Description */
      description: string | null;
      /** Enabled */
      enabled: boolean;
      /** Is Mock */
      is_mock: boolean;
      /** Key */
      key: string;
      kind: components["schemas"]["SourceKind"];
      /** Last Counts */
      last_counts: {
        [key: string]: unknown;
      };
      /** Last Error */
      last_error: string | null;
      /** Last Run At */
      last_run_at: string | null;
      /** Last Status */
      last_status: string | null;
      /** Name */
      name: string;
      /** Notes */
      notes: string | null;
      policy: components["schemas"]["SourcePolicy"];
      /** Priority */
      priority: number;
      /** Rate Limit Per Minute */
      rate_limit_per_minute: number;
      /** Runnable */
      runnable: boolean;
      /** Skip Reason */
      skip_reason: string | null;
    };
    /** JobStats */
    JobStats: {
      /** By Source */
      by_source: {
        [key: string]: number;
      };
      /**
       * Duplicates
       * @description Duplicate listings linked to a primary record
       */
      duplicates: number;
      /**
       * Found Today
       * @description Jobs discovered since midnight (TIMEZONE)
       */
      found_today: number;
      /**
       * In Window
       * @description Jobs posted within JOB_LOOKBACK_HOURS
       */
      in_window: number;
      last_discovery: components["schemas"]["LastDiscovery"] | null;
      /**
       * Total
       * @description Primary job records (duplicates excluded)
       */
      total: number;
      /** Unknown Date */
      unknown_date: number;
      window: components["schemas"]["WindowRead"];
    };
    /**
     * LanguageLevel
     * @enum {string}
     */
    LanguageLevel: "native" | "fluent" | "professional" | "intermediate" | "basic";
    /** LastDiscovery */
    LastDiscovery: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Finished At */
      finished_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Jobs Discovered */
      jobs_discovered: number;
      status: components["schemas"]["RunStatus"];
    };
    /** LivenessResponse */
    LivenessResponse: {
      /** Service */
      service: string;
      /**
       * Status
       * @default ok
       * @constant
       */
      status: "ok";
      /** Version */
      version: string;
    };
    /** Location */
    "Location-Input": {
      /** City */
      city?: string | null;
      /** Country */
      country?: string | null;
      /** Country Code */
      country_code?: string | null;
    };
    /** Location */
    "Location-Output": {
      /** City */
      city: string | null;
      /** Country */
      country: string | null;
      /** Country Code */
      country_code: string | null;
    };
    /** OtherSection */
    "OtherSection-Input": {
      /** Heading */
      heading: string;
      /** Lines */
      lines?: string[];
    };
    /** OtherSection */
    "OtherSection-Output": {
      /** Heading */
      heading: string;
      /** Lines */
      lines: string[];
    };
    /** ParsedCV */
    "ParsedCV-Input": {
      /** Certifications */
      certifications?: string[];
      contact?: components["schemas"]["ContactInfo-Input"];
      /** Education */
      education?: components["schemas"]["EducationEntry-Input"][];
      /** Experiences */
      experiences?: components["schemas"]["ExperienceEntry-Input"][];
      /** Header Lines */
      header_lines?: string[];
      /**
       * Language
       * @default unknown
       */
      language: string;
      /** Languages */
      languages?: string[];
      /** Other Sections */
      other_sections?: components["schemas"]["OtherSection-Input"][];
      /** Parser Version */
      parser_version: string;
      /** Projects */
      projects?: components["schemas"]["ProjectEntry-Input"][];
      /** Skills */
      skills?: components["schemas"]["SkillItem-Input"][];
      /** Summary */
      summary?: string | null;
      /** Warnings */
      warnings?: string[];
    };
    /** ParsedCV */
    "ParsedCV-Output": {
      /** Certifications */
      certifications: string[];
      contact: components["schemas"]["ContactInfo-Output"];
      /** Education */
      education: components["schemas"]["EducationEntry-Output"][];
      /** Experiences */
      experiences: components["schemas"]["ExperienceEntry-Output"][];
      /** Header Lines */
      header_lines: string[];
      /**
       * Language
       * @default unknown
       */
      language: string;
      /** Languages */
      languages: string[];
      /** Other Sections */
      other_sections: components["schemas"]["OtherSection-Output"][];
      /** Parser Version */
      parser_version: string;
      /** Projects */
      projects: components["schemas"]["ProjectEntry-Output"][];
      /** Skills */
      skills: components["schemas"]["SkillItem-Output"][];
      /** Summary */
      summary: string | null;
      /** Warnings */
      warnings: string[];
    };
    /** PhaseInfo */
    PhaseInfo: {
      /** Name */
      name: string;
      /** Number */
      number: number;
      /** Status */
      status: string;
      /** Summary */
      summary: string;
    };
    /**
     * PostingDateStatus
     * @enum {string}
     */
    PostingDateStatus: "KNOWN" | "ESTIMATED" | "UNKNOWN";
    /** ProjectEntry */
    "ProjectEntry-Input": {
      /** Bullets */
      bullets?: string[];
      dates?: components["schemas"]["DateRange-Input"] | null;
      /** Details */
      details?: string[];
      /** Name */
      name: string;
    };
    /** ProjectEntry */
    "ProjectEntry-Output": {
      /** Bullets */
      bullets: string[];
      dates: components["schemas"]["DateRange-Output"] | null;
      /** Details */
      details: string[];
      /** Name */
      name: string;
    };
    /** ReadinessResponse */
    ReadinessResponse: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Components */
      components: components["schemas"]["ComponentHealth"][];
      status: components["schemas"]["ComponentStatus"];
    };
    /** Relocation */
    "Relocation-Input": {
      /** Willing To Relocate */
      willing_to_relocate?: boolean | null;
    };
    /** Relocation */
    "Relocation-Output": {
      /** Willing To Relocate */
      willing_to_relocate: boolean | null;
    };
    /**
     * RemoteStatus
     * @enum {string}
     */
    RemoteStatus: "REMOTE" | "HYBRID" | "ONSITE" | "UNKNOWN";
    /** RunCreated */
    RunCreated: {
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      status: components["schemas"]["RunStatus"];
      /** Task Id */
      task_id: string | null;
    };
    /** RunDetail */
    RunDetail: {
      /** Applications Prepared */
      applications_prepared: number;
      /** Applications Submitted */
      applications_submitted: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Cv Generated */
      cv_generated: number;
      /** Duration Seconds */
      duration_seconds: number | null;
      /** Error Count */
      error_count: number;
      /** Errors */
      errors: components["schemas"]["RunError"][];
      /** Events */
      events: components["schemas"]["RunEventOut"][];
      /** Finished At */
      finished_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Jobs Discovered */
      jobs_discovered: number;
      /** Jobs Processed */
      jobs_processed: number;
      /** Jobs Qualified */
      jobs_qualified: number;
      /** Parameters */
      parameters: {
        [key: string]: unknown;
      };
      run_type: components["schemas"]["RunType"];
      /** Started At */
      started_at: string | null;
      status: components["schemas"]["RunStatus"];
      /** Summary */
      summary: {
        [key: string]: unknown;
      };
      /** Task Id */
      task_id: string | null;
      trigger: components["schemas"]["RunTrigger"];
    };
    /** RunError */
    RunError: {
      /**
       * At
       * Format: date-time
       */
      at: string;
      /** Message */
      message: string;
      /** Stage */
      stage: string;
      /** Type */
      type: string;
    };
    /** RunEventOut */
    RunEventOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Data */
      data: {
        [key: string]: unknown;
      };
      /**
       * Id
       * Format: uuid
       */
      id: string;
      level: components["schemas"]["EventLevel"];
      /** Message */
      message: string;
      /** Sequence */
      sequence: number;
      /** Stage */
      stage: string;
    };
    /** RunPage */
    RunPage: {
      /** Items */
      items: components["schemas"]["RunSummary"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /**
     * RunStatus
     * @enum {string}
     */
    RunStatus: "PENDING" | "RUNNING" | "SUCCEEDED" | "PARTIAL_SUCCESS" | "FAILED" | "CANCELLED";
    /** RunSummary */
    RunSummary: {
      /** Applications Prepared */
      applications_prepared: number;
      /** Applications Submitted */
      applications_submitted: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Cv Generated */
      cv_generated: number;
      /** Duration Seconds */
      duration_seconds: number | null;
      /** Error Count */
      error_count: number;
      /** Finished At */
      finished_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Jobs Discovered */
      jobs_discovered: number;
      /** Jobs Processed */
      jobs_processed: number;
      /** Jobs Qualified */
      jobs_qualified: number;
      run_type: components["schemas"]["RunType"];
      /** Started At */
      started_at: string | null;
      status: components["schemas"]["RunStatus"];
      /** Task Id */
      task_id: string | null;
      trigger: components["schemas"]["RunTrigger"];
    };
    /**
     * RunTrigger
     * @enum {string}
     */
    RunTrigger: "MANUAL" | "SCHEDULED" | "API" | "SYSTEM";
    /**
     * RunType
     * @enum {string}
     */
    RunType:
      | "DIAGNOSTIC"
      | "DAILY_PIPELINE"
      | "DISCOVERY"
      | "ANALYSIS"
      | "CV_GENERATION"
      | "APPLICATION_PREPARATION"
      | "SUBMISSION";
    /** SalaryExpectation */
    "SalaryExpectation-Input": {
      /**
       * Country Code
       * @description Applies to this country only; null = default
       */
      country_code?: string | null;
      /** Currency */
      currency: string;
      /** Maximum */
      maximum?: number | null;
      /** Minimum */
      minimum: number;
      /** Note */
      note?: string | null;
      /**
       * Period
       * @default year
       * @enum {string}
       */
      period: "year" | "month";
    };
    /** SalaryExpectation */
    "SalaryExpectation-Output": {
      /**
       * Country Code
       * @description Applies to this country only; null = default
       */
      country_code: string | null;
      /** Currency */
      currency: string;
      /** Maximum */
      maximum: number | null;
      /** Minimum */
      minimum: number;
      /** Note */
      note: string | null;
      /**
       * Period
       * @default year
       * @enum {string}
       */
      period: "year" | "month";
    };
    /**
     * SecretsStatus
     * @description Whether each secret is configured — values are never exposed.
     */
    SecretsStatus: {
      /** Anthropic Api Key */
      anthropic_api_key: boolean;
      /** Api Auth Token */
      api_auth_token: boolean;
      /** Encryption Key */
      encryption_key: boolean;
      /** N8N Webhook Secret */
      n8n_webhook_secret: boolean;
      /** Smtp Password */
      smtp_password: boolean;
      /** Telegram Bot Token */
      telegram_bot_token: boolean;
    };
    /**
     * Seniority
     * @enum {string}
     */
    Seniority: "INTERN" | "JUNIOR" | "MID" | "SENIOR" | "LEAD" | "PRINCIPAL" | "UNKNOWN";
    /** SkillItem */
    "SkillItem-Input": {
      /** Category */
      category?: string | null;
      /** Name */
      name: string;
    };
    /** SkillItem */
    "SkillItem-Output": {
      /** Category */
      category: string | null;
      /** Name */
      name: string;
    };
    /**
     * SkillSource
     * @enum {string}
     */
    SkillSource: "MASTER_CV" | "PROFILE_DECLARED";
    /**
     * SkillStrength
     * @enum {string}
     */
    SkillStrength: "NONE" | "LISTED" | "DEMONSTRATED";
    /**
     * SourceKind
     * @enum {string}
     */
    SourceKind: "ATS_API" | "CAREER_PAGE" | "FEED" | "MANUAL";
    /**
     * SourcePolicy
     * @enum {string}
     */
    SourcePolicy: "api_only" | "allowed" | "manual_only" | "disabled";
    /** SpokenLanguage */
    SpokenLanguage: {
      /** Language */
      language: string;
      level: components["schemas"]["LanguageLevel"];
    };
    /** SystemConfig */
    SystemConfig: {
      /** Ats Max Iterations */
      ats_max_iterations: number;
      /** Ats Target Score */
      ats_target_score: number;
      /** Daily Run Time */
      daily_run_time: string;
      /** Job Lookback Hours */
      job_lookback_hours: number;
      /** Llm Model */
      llm_model: string;
      /** Llm Provider */
      llm_provider: string;
      /** Log Format */
      log_format: string;
      /** Log Level */
      log_level: string;
      /** Max Upload Mb */
      max_upload_mb: number;
      /** Notification Channels */
      notification_channels: string[];
      /** Scheduler Enabled */
      scheduler_enabled: boolean;
      /** Storage Backend */
      storage_backend: string;
      /** Timezone */
      timezone: string;
    };
    /** SystemInfo */
    SystemInfo: {
      /** Api Prefix */
      api_prefix: string;
      /** Auth Enabled */
      auth_enabled: boolean;
      /** Auto Submit */
      auto_submit: boolean;
      config: components["schemas"]["SystemConfig"];
      /** Environment */
      environment: string;
      /** Mock Mode */
      mock_mode: boolean;
      /** Name */
      name: string;
      /** Phases */
      phases: components["schemas"]["PhaseInfo"][];
      secrets: components["schemas"]["SecretsStatus"];
      /** Version */
      version: string;
      /** Warnings */
      warnings: string[];
    };
    /** SystemStatus */
    SystemStatus: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Components */
      components: components["schemas"]["ComponentHealth"][];
      status: components["schemas"]["ComponentStatus"];
    };
    /** TargetCountries */
    "TargetCountries-Input": {
      /** Primary */
      primary?: components["schemas"]["TargetCountry-Input"][];
      /** Secondary */
      secondary?: components["schemas"]["TargetCountry-Input"][];
    };
    /** TargetCountries */
    "TargetCountries-Output": {
      /** Primary */
      primary: components["schemas"]["TargetCountry-Output"][];
      /** Secondary */
      secondary: components["schemas"]["TargetCountry-Output"][];
    };
    /** TargetCountry */
    "TargetCountry-Input": {
      /**
       * Code
       * @description ISO 3166-1 alpha-2 country code
       * @example FR
       */
      code: string;
      /** Name */
      name: string;
    };
    /** TargetCountry */
    "TargetCountry-Output": {
      /**
       * Code
       * @description ISO 3166-1 alpha-2 country code
       * @example FR
       */
      code: string;
      /** Name */
      name: string;
    };
    /** Targets */
    "Targets-Input": {
      countries?: components["schemas"]["TargetCountries-Input"];
      /** Roles */
      roles?: string[];
    };
    /** Targets */
    "Targets-Output": {
      countries: components["schemas"]["TargetCountries-Output"];
      /** Roles */
      roles: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WindowRead */
    WindowRead: {
      /** Lookback Hours */
      lookback_hours: number;
      /**
       * Posted After
       * Format: date-time
       */
      posted_after: string;
      /**
       * Posted Before
       * Format: date-time
       */
      posted_before: string;
    };
    /**
     * WindowStatus
     * @enum {string}
     */
    WindowStatus: "IN_WINDOW" | "OUT_OF_WINDOW" | "UNKNOWN_DATE";
    /** WorkAuthorization */
    "WorkAuthorization-Input": {
      /** Current Work Authorizations */
      current_work_authorizations?: components["schemas"]["WorkAuthorizationEntry-Input"][];
      /** Sponsorship Required When */
      sponsorship_required_when?: ("always" | "work_permit_needed" | "never") | null;
      /** Visa Sponsorship Required */
      visa_sponsorship_required?: boolean | null;
    };
    /** WorkAuthorization */
    "WorkAuthorization-Output": {
      /** Current Work Authorizations */
      current_work_authorizations: components["schemas"]["WorkAuthorizationEntry-Output"][];
      /** Sponsorship Required When */
      sponsorship_required_when: ("always" | "work_permit_needed" | "never") | null;
      /** Visa Sponsorship Required */
      visa_sponsorship_required: boolean | null;
    };
    /** WorkAuthorizationEntry */
    "WorkAuthorizationEntry-Input": {
      /**
       * Country Code
       * @description ISO 3166-1 alpha-2 country code
       * @example FR
       */
      country_code: string;
      status: components["schemas"]["AuthorizationStatus"];
    };
    /** WorkAuthorizationEntry */
    "WorkAuthorizationEntry-Output": {
      /**
       * Country Code
       * @description ISO 3166-1 alpha-2 country code
       * @example FR
       */
      country_code: string;
      status: components["schemas"]["AuthorizationStatus"];
    };
    /**
     * WorkMode
     * @enum {string}
     */
    WorkMode: "onsite" | "hybrid" | "remote";
    /** YearMonth */
    "YearMonth-Input": {
      /** Month */
      month?: number | null;
      /** Year */
      year: number;
    };
    /** YearMonth */
    "YearMonth-Output": {
      /** Month */
      month: number | null;
      /** Year */
      year: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_audit_logs_api_v1_audit_logs_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        action?: string | null;
        entity_type?: string | null;
        entity_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditLogPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_candidate_api_v1_candidate_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CandidateRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_candidate_api_v1_candidate_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CandidateUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CandidateRead"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  export_candidate_api_v1_candidate_export_get: {
    parameters: {
      query?: {
        /** @description Include contact details */
        include_private?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/yaml": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  import_candidate_api_v1_candidate_import_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CandidateRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_master_cvs_api_v1_candidate_master_cv_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CvVersionSummary"][];
        };
      };
    };
  };
  upload_master_cv_api_v1_candidate_master_cv_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_master_cv_api_v1_candidate_master_cv_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CvVersionDetail"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unsupported Media Type */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_master_cv_api_v1_candidate_master_cv__version_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CvVersionDetail"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  confirm_master_cv_api_v1_candidate_master_cv__version_id__confirm_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CvVersionDetail"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  download_master_cv_api_v1_candidate_master_cv__version_id__file_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": unknown;
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revise_master_cv_api_v1_candidate_master_cv__version_id__revise_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CvVersionDetail"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_master_cv_structure_api_v1_candidate_master_cv__version_id__structure_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ParsedCV-Input"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CvVersionDetail"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_skills_api_v1_candidate_skills_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CandidateSkillRead"][];
        };
      };
    };
  };
  list_companies_api_v1_companies_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompanyRead"][];
        };
      };
    };
  };
  create_company_api_v1_companies_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompanyCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompanyRead"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  import_companies_api_v1_companies_import_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompanyImportResult"];
        };
      };
    };
  };
  get_company_api_v1_companies__company_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        company_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompanyRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_company_api_v1_companies__company_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        company_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_company_api_v1_companies__company_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        company_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompanyUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompanyRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  live_api_v1_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LivenessResponse"];
        };
      };
    };
  };
  ready_api_v1_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
      /** @description A critical dependency is down */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
    };
  };
  list_job_sources_api_v1_job_sources_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobSourceRead"][];
        };
      };
    };
  };
  list_jobs_api_v1_jobs_get: {
    parameters: {
      query?: {
        window?: "in_window" | "out_of_window" | "all";
        date_status?: components["schemas"]["PostingDateStatus"] | null;
        source?: string | null;
        country?: string | null;
        q?: string | null;
        company_id?: string | null;
        include_duplicates?: boolean;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  import_job_api_v1_jobs_import_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JobImportRequest"];
      };
    };
    responses: {
      /** @description The posting was already known */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobImportResult"];
        };
      };
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobImportResult"];
        };
      };
      /** @description Invalid or unsafe URL */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  import_email_api_v1_jobs_import_email_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailImportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailImportResult"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  job_stats_api_v1_jobs_stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobStats"];
        };
      };
    };
  };
  get_job_api_v1_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobDetail"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  track_job_api_v1_jobs__job_id__track_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobApplicationRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_runs_api_v1_runs_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        status?: components["schemas"]["RunStatus"] | null;
        run_type?: components["schemas"]["RunType"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_diagnostic_api_v1_runs_diagnostic_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunCreated"];
        };
      };
      /** @description The task queue is unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  start_discovery_api_v1_runs_discovery_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunCreated"];
        };
      };
      /** @description The task queue is unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_run_api_v1_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  system_info_api_v1_system_info_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SystemInfo"];
        };
      };
    };
  };
  system_status_api_v1_system_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SystemStatus"];
        };
      };
    };
  };
}
