/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/audit-logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List audit entries (newest first) */
    get: operations["list_audit_logs_api_v1_audit_logs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness probe
     * @description The process is up and serving requests.
     */
    get: operations["live_api_v1_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness probe
     * @description Database reachable, migrations at head, Redis reachable, storage writable.
     *
     *     Public endpoint: failure details are hidden (see `/system/status` for details).
     */
    get: operations["ready_api_v1_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List automation runs (newest first) */
    get: operations["list_runs_api_v1_runs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/diagnostic": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a system self-test run on a worker */
    post: operations["start_diagnostic_api_v1_runs_diagnostic_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Run detail with its event timeline */
    get: operations["get_run_api_v1_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/system/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Safe configuration and roadmap */
    get: operations["system_info_api_v1_system_info_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/system/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detailed component health */
    get: operations["system_status_api_v1_system_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AuditLogEntry */
    AuditLogEntry: {
      /** Action */
      action: string;
      /** Actor */
      actor: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Details */
      details: {
        [key: string]: unknown;
      };
      /** Entity Id */
      entity_id: string | null;
      /** Entity Type */
      entity_type: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Request Id */
      request_id: string | null;
      /** Sequence */
      sequence: number;
    };
    /** AuditLogPage */
    AuditLogPage: {
      /** Items */
      items: components["schemas"]["AuditLogEntry"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** ComponentHealth */
    ComponentHealth: {
      /** Critical */
      critical: boolean;
      /** Detail */
      detail?: string | null;
      /** Latency Ms */
      latency_ms?: number | null;
      /** Name */
      name: string;
      status: components["schemas"]["ComponentStatus"];
    };
    /**
     * ComponentStatus
     * @enum {string}
     */
    ComponentStatus: "ok" | "degraded" | "down";
    /** ErrorDetail */
    ErrorDetail: {
      /**
       * Code
       * @description Stable machine-readable error code
       */
      code: string;
      /** Details */
      details?: unknown | null;
      /** Message */
      message: string;
      /** Request Id */
      request_id?: string | null;
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components["schemas"]["ErrorDetail"];
    };
    /**
     * EventLevel
     * @enum {string}
     */
    EventLevel: "DEBUG" | "INFO" | "WARNING" | "ERROR";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LivenessResponse */
    LivenessResponse: {
      /** Service */
      service: string;
      /**
       * Status
       * @default ok
       * @constant
       */
      status: "ok";
      /** Version */
      version: string;
    };
    /** PhaseInfo */
    PhaseInfo: {
      /** Name */
      name: string;
      /** Number */
      number: number;
      /** Status */
      status: string;
      /** Summary */
      summary: string;
    };
    /** ReadinessResponse */
    ReadinessResponse: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Components */
      components: components["schemas"]["ComponentHealth"][];
      status: components["schemas"]["ComponentStatus"];
    };
    /** RunCreated */
    RunCreated: {
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      status: components["schemas"]["RunStatus"];
      /** Task Id */
      task_id: string | null;
    };
    /** RunDetail */
    RunDetail: {
      /** Applications Prepared */
      applications_prepared: number;
      /** Applications Submitted */
      applications_submitted: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Cv Generated */
      cv_generated: number;
      /** Duration Seconds */
      duration_seconds: number | null;
      /** Error Count */
      error_count: number;
      /** Errors */
      errors: components["schemas"]["RunError"][];
      /** Events */
      events: components["schemas"]["RunEventOut"][];
      /** Finished At */
      finished_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Jobs Discovered */
      jobs_discovered: number;
      /** Jobs Processed */
      jobs_processed: number;
      /** Jobs Qualified */
      jobs_qualified: number;
      /** Parameters */
      parameters: {
        [key: string]: unknown;
      };
      run_type: components["schemas"]["RunType"];
      /** Started At */
      started_at: string | null;
      status: components["schemas"]["RunStatus"];
      /** Summary */
      summary: {
        [key: string]: unknown;
      };
      /** Task Id */
      task_id: string | null;
      trigger: components["schemas"]["RunTrigger"];
    };
    /** RunError */
    RunError: {
      /**
       * At
       * Format: date-time
       */
      at: string;
      /** Message */
      message: string;
      /** Stage */
      stage: string;
      /** Type */
      type: string;
    };
    /** RunEventOut */
    RunEventOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Data */
      data: {
        [key: string]: unknown;
      };
      /**
       * Id
       * Format: uuid
       */
      id: string;
      level: components["schemas"]["EventLevel"];
      /** Message */
      message: string;
      /** Sequence */
      sequence: number;
      /** Stage */
      stage: string;
    };
    /** RunPage */
    RunPage: {
      /** Items */
      items: components["schemas"]["RunSummary"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /**
     * RunStatus
     * @enum {string}
     */
    RunStatus: "PENDING" | "RUNNING" | "SUCCEEDED" | "PARTIAL_SUCCESS" | "FAILED" | "CANCELLED";
    /** RunSummary */
    RunSummary: {
      /** Applications Prepared */
      applications_prepared: number;
      /** Applications Submitted */
      applications_submitted: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Cv Generated */
      cv_generated: number;
      /** Duration Seconds */
      duration_seconds: number | null;
      /** Error Count */
      error_count: number;
      /** Finished At */
      finished_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Jobs Discovered */
      jobs_discovered: number;
      /** Jobs Processed */
      jobs_processed: number;
      /** Jobs Qualified */
      jobs_qualified: number;
      run_type: components["schemas"]["RunType"];
      /** Started At */
      started_at: string | null;
      status: components["schemas"]["RunStatus"];
      /** Task Id */
      task_id: string | null;
      trigger: components["schemas"]["RunTrigger"];
    };
    /**
     * RunTrigger
     * @enum {string}
     */
    RunTrigger: "MANUAL" | "SCHEDULED" | "API" | "SYSTEM";
    /**
     * RunType
     * @enum {string}
     */
    RunType:
      | "DIAGNOSTIC"
      | "DAILY_PIPELINE"
      | "DISCOVERY"
      | "ANALYSIS"
      | "CV_GENERATION"
      | "APPLICATION_PREPARATION"
      | "SUBMISSION";
    /**
     * SecretsStatus
     * @description Whether each secret is configured — values are never exposed.
     */
    SecretsStatus: {
      /** Anthropic Api Key */
      anthropic_api_key: boolean;
      /** Api Auth Token */
      api_auth_token: boolean;
      /** Encryption Key */
      encryption_key: boolean;
      /** N8N Webhook Secret */
      n8n_webhook_secret: boolean;
      /** Smtp Password */
      smtp_password: boolean;
      /** Telegram Bot Token */
      telegram_bot_token: boolean;
    };
    /** SystemConfig */
    SystemConfig: {
      /** Ats Max Iterations */
      ats_max_iterations: number;
      /** Ats Target Score */
      ats_target_score: number;
      /** Daily Run Time */
      daily_run_time: string;
      /** Job Lookback Hours */
      job_lookback_hours: number;
      /** Llm Model */
      llm_model: string;
      /** Llm Provider */
      llm_provider: string;
      /** Log Format */
      log_format: string;
      /** Log Level */
      log_level: string;
      /** Notification Channels */
      notification_channels: string[];
      /** Scheduler Enabled */
      scheduler_enabled: boolean;
      /** Storage Backend */
      storage_backend: string;
      /** Timezone */
      timezone: string;
    };
    /** SystemInfo */
    SystemInfo: {
      /** Api Prefix */
      api_prefix: string;
      /** Auth Enabled */
      auth_enabled: boolean;
      /** Auto Submit */
      auto_submit: boolean;
      config: components["schemas"]["SystemConfig"];
      /** Environment */
      environment: string;
      /** Mock Mode */
      mock_mode: boolean;
      /** Name */
      name: string;
      /** Phases */
      phases: components["schemas"]["PhaseInfo"][];
      secrets: components["schemas"]["SecretsStatus"];
      /** Version */
      version: string;
      /** Warnings */
      warnings: string[];
    };
    /** SystemStatus */
    SystemStatus: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Components */
      components: components["schemas"]["ComponentHealth"][];
      status: components["schemas"]["ComponentStatus"];
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_audit_logs_api_v1_audit_logs_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        action?: string | null;
        entity_type?: string | null;
        entity_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditLogPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  live_api_v1_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LivenessResponse"];
        };
      };
    };
  };
  ready_api_v1_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
      /** @description A critical dependency is down */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
    };
  };
  list_runs_api_v1_runs_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        status?: components["schemas"]["RunStatus"] | null;
        run_type?: components["schemas"]["RunType"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_diagnostic_api_v1_runs_diagnostic_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunCreated"];
        };
      };
      /** @description The task queue is unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_run_api_v1_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  system_info_api_v1_system_info_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SystemInfo"];
        };
      };
    };
  };
  system_status_api_v1_system_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SystemStatus"];
        };
      };
    };
  };
}
